import { CrmDatabase } from "@/types/crm";

export function getInitialSeedData(): CrmDatabase {
  const now = new Date();
  const subDays = (d: number) => new Date(now.getTime() - d * 24 * 60 * 60 * 1000).toISOString();
  const addDays = (d: number) => new Date(now.getTime() + d * 24 * 60 * 60 * 1000).toISOString();

  return {
    users: [
      {
        id: "usr_admin",
        name: "Quản Trị Viên",
        email: "admin@zencrm.vn",
        role: "ADMIN",
        avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80",
        phone: "0901234567",
        isLocked: false,
        password: "zengarden",
        targetRevenue: 0,
        targetDeals: 0,
      },
    ],

    teams: [],

    sources: [
      "Quảng cáo Facebook",
      "Google Ads",
      "Hội Nhóm Thủy Sinh (Facebook Group)",
      "Website / Tự đến cửa hàng",
      "Triển lãm / Hội thi Thủy sinh",
      "Zalo OA",
      "Giới thiệu (Referral)",
      "Khác",
    ],

    statuses: [
      { id: "NEW", name: "Mới tiếp nhận", color: "#3b82f6" },
      { id: "CONSULTING", name: "Đang tư vấn", color: "#eab308" },
      { id: "POTENTIAL", name: "Tiềm năng", color: "#a855f7" },
      { id: "WON", name: "Đã chốt", color: "#22c55e", isWon: true },
      { id: "LOST", name: "Đã hủy", color: "#ef4444", isLost: true },
      { id: "COMPLETED", name: "Đã hoàn thành", color: "#0ea5e9", isWon: true },
    ],

    productCategories: [
      "Ráy & Dương Xỉ",
      "Bucephalandra & Tiêu Thảo",
      "Cây Tiền Cảnh (Trải thảm)",
      "Cây Cắt Cắm Hậu Cảnh",
      "Rêu Thủy Sinh (Moss)",
      "Setup Hồ Trọn Gói & Bảo Dưỡng",
    ],

    pipelines: [
      {
        id: "pl_standard",
        name: "Pipeline Bán Cây Thủy Sinh & Đại Lý Sỉ",
        isDefault: true,
        stages: [
          { id: "stg_approach", name: "Tiếp nhận nhu cầu", order: 1, defaultProbability: 20, color: "#3b82f6" },
          { id: "stg_consult", name: "Tư vấn cây & bể", order: 2, defaultProbability: 40, color: "#eab308" },
          { id: "stg_quote", name: "Gửi báo giá sỉ/lẻ", order: 3, defaultProbability: 60, color: "#a855f7" },
          { id: "stg_negotiate", name: "Chốt số lượng & Đóng gói", order: 4, defaultProbability: 80, color: "#f97316" },
          { id: "stg_won", name: "Chốt đơn thành công", order: 5, defaultProbability: 100, color: "#22c55e", isWon: true },
          { id: "stg_lost", name: "Thua deal / Khách hủy", order: 6, defaultProbability: 0, color: "#ef4444", isLost: true },
        ],
      },
      {
        id: "pl_enterprise",
        name: "Pipeline Dự Án Setup Hồ Thủy Sinh Trọn Gói",
        isDefault: false,
        stages: [
          { id: "stg_ent_qualify", name: "Khảo sát không gian", order: 1, defaultProbability: 25, color: "#3b82f6" },
          { id: "stg_ent_demo", name: "Phác thảo layout 3D & chọn cây", order: 2, defaultProbability: 50, color: "#8b5cf6" },
          { id: "stg_ent_proposal", name: "Dự toán & Hợp đồng thi công", order: 3, defaultProbability: 75, color: "#f59e0b" },
          { id: "stg_ent_won", name: "Bàn giao & Nghiệm thu bể", order: 4, defaultProbability: 100, color: "#10b981", isWon: true },
          { id: "stg_ent_lost", name: "Khách hủy kế hoạch", order: 5, defaultProbability: 0, color: "#ef4444", isLost: true },
        ],
      },
    ],

    leads: [],

    notes: [],

    auditLogs: [],

    products: [
      {
        id: "prod_ray_petite",
        sku: "TS-RAY-PETITE",
        name: "Ráy Nana Petite (Anubias barteri var. nana 'Petite')",
        category: "Ráy & Dương Xỉ",
        description: "Dòng ráy lá siêu nhỏ, phát triển chậm, bám lũa đá cực đẹp, chịu ánh sáng yếu và không kén nước.",
        unit: "Chậu",
        retailPrice: 85000,
        wholesalePrice: 65000,
        vipPrice: 55000,
        isActive: true,
        imageUrl: "https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=600&auto=format&fit=crop&q=80",
        notes: "Ánh sáng: Yếu - Vừa (0.5W/L) | CO2: Không bắt buộc | Trồng bám lũa, dán đá | Bảo hành 1 đổi 1 nếu dập úng khi ship tỉnh",
      },
      {
        id: "prod_ray_pinto",
        sku: "TS-RAY-PINTO",
        name: "Ráy Lá Cẩm Thạch Pinto (Anubias barteri 'Pinto')",
        category: "Ráy & Dương Xỉ",
        description: "Dòng ráy đột biến cẩm thạch trắng hiếm, sang trọng, màu trắng sữa xen lẫn xanh ngọc lục bảo.",
        unit: "Chậu",
        retailPrice: 350000,
        wholesalePrice: 280000,
        vipPrice: 250000,
        isActive: true,
        imageUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&auto=format&fit=crop&q=80",
        notes: "Dòng đột biến lá trắng cẩm thạch cực hiếm | Cần ánh sáng khá để giữ vân trắng sắc nét | Tặng phân vi lượng khi mua từ 2 chậu",
      },
      {
        id: "prod_dx_trident",
        sku: "TS-DX-TRIDENT",
        name: "Dương Xỉ Trident Lá Hẹp (Microsorum pteropus 'Trident')",
        category: "Ráy & Dương Xỉ",
        description: "Lá chẻ 3 thùy thanh mảnh, thích hợp buộc lũa trung cảnh tạo chiều sâu rừng rậm cho bể thủy sinh.",
        unit: "Bụi",
        retailPrice: 120000,
        wholesalePrice: 90000,
        vipPrice: 80000,
        isActive: true,
        imageUrl: "https://images.unsplash.com/photo-1520302630591-fd1c66edc19d?w=600&auto=format&fit=crop&q=80",
        notes: "Lá chẻ 3 thùy thanh mảnh | Buộc lũa trung cảnh tạo chiều sâu rừng rậm | Dễ chăm, không kén nước",
      },
      {
        id: "prod_bucep_ghost",
        sku: "TS-BUCEP-GHOST",
        name: "Bucephalandra Brownie Ghost 2011 (Tím Ánh Kim)",
        category: "Bucephalandra & Tiêu Thảo",
        description: "Dòng Bucep huyền thoại màu tím đậm ánh kim kim tuyến dưới đèn RGB, cây khỏe, dưỡng form chuẩn tại trại.",
        unit: "Bụi/Ngọn",
        retailPrice: 250000,
        wholesalePrice: 190000,
        vipPrice: 170000,
        isActive: true,
        imageUrl: "https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=600&auto=format&fit=crop&q=80",
        notes: "Bucep Brownie Ghost 2011 huyền thoại | Ánh kim tím ngắt dưới đèn RGB | Đã dưỡng nước thuần 60 ngày tại trại Zen",
      },
      {
        id: "prod_tthao_flamingo",
        sku: "TS-TTHAO-FLAMINGO",
        name: "Tiêu Thảo Flamingo Hồng Hạc (Cấy Mô In-Vitro)",
        category: "Bucephalandra & Tiêu Thảo",
        description: "Cây cấy mô màu hồng cánh sen rực rỡ, sạch mầm bệnh và ốc hại, tạo điểm nhấn tiền cảnh tuyệt mỹ.",
        unit: "Cốc In-Vitro",
        retailPrice: 180000,
        wholesalePrice: 140000,
        vipPrice: 125000,
        isActive: true,
        imageUrl: "https://images.unsplash.com/photo-1516684732162-798a0062be99?w=600&auto=format&fit=crop&q=80",
        notes: "Cấy mô In-Vitro vô trùng 100% sạch ốc hại | Cần ánh sáng khá & CO2 để lên hồng rực rỡ | Đóng gói hộp gel chuyên dụng",
      },
      {
        id: "prod_tc_montecarlo",
        sku: "TS-TC-MONTECARLO",
        name: "Trân Châu Ngọc Trai (Micranthemum 'Monte Carlo')",
        category: "Cây Tiền Cảnh (Trải thảm)",
        description: "Cây tiền cảnh bò thảm xanh mướt, lá tròn bóng bẩy, dễ trồng hơn trân châu Cuba, chịu nhiệt tốt.",
        unit: "Hộp/Cốc",
        retailPrice: 60000,
        wholesalePrice: 45000,
        vipPrice: 38000,
        isActive: true,
        imageUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80",
        notes: "Bò thảm tiền cảnh xanh mướt | Chịu nhiệt độ tới 28°C tốt | 1 cốc cắm phủ 20x20cm sau 3 tuần",
      },
      {
        id: "prod_tc_nguuma",
        sku: "TS-TC-NGUUMA",
        name: "Cỏ Ngưu Ma Vương Lùn Xòe (Eleocharis acicularis 'Mini')",
        category: "Cây Tiền Cảnh (Trải thảm)",
        description: "Dáng cỏ tự nhiên như thảo nguyên xanh, mọc lùn xòe sát đáy nền không cần cắt tỉa nhiều lần.",
        unit: "Cốc",
        retailPrice: 75000,
        wholesalePrice: 55000,
        vipPrice: 48000,
        isActive: true,
        imageUrl: "https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?w=600&auto=format&fit=crop&q=80",
        notes: "Cỏ lùn xòe tự nhiên phong cách Iwagumi | Không cần cắt tỉa nhiều | Gốc rễ đã phát triển khỏe",
      },
      {
        id: "prod_cc_vayoc",
        sku: "TS-CC-VAYOC",
        name: "Vảy Ốc Đỏ H'ra (Rotala rotundifolia 'H'ra')",
        category: "Cây Cắt Cắm Hậu Cảnh",
        description: "Dòng cây cắt cắm hậu cảnh ngả màu đỏ rực như ráng chiều khi đủ ánh sáng và CO2, dễ nhân giống.",
        unit: "Bó (25 ngọn)",
        retailPrice: 50000,
        wholesalePrice: 35000,
        vipPrice: 30000,
        isActive: true,
        imageUrl: "https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=600&auto=format&fit=crop&q=80",
        notes: "Cây cắt cắm hậu cảnh ngả đỏ rực | Bó 25 ngọn ra rễ khỏe | Thích hợp tạo bụi hậu cảnh rực rỡ",
      },
      {
        id: "prod_reu_minifiss",
        sku: "TS-REU-MINIFISS",
        name: "Rêu Minifiss Cánh Phượng Dán Vỉ (Fissidens splachnobryoides)",
        category: "Rêu Thủy Sinh (Moss)",
        description: "Rêu lá kim hình cánh phượng mini đã dán vỉ lưới inox 10x10cm sẵn sàng hạ thủy phủ xanh mặt đá layout.",
        unit: "Vỉ 10x10cm",
        retailPrice: 95000,
        wholesalePrice: 75000,
        vipPrice: 65000,
        isActive: true,
        imageUrl: "https://images.unsplash.com/photo-1520302630591-fd1c66edc19d?w=600&auto=format&fit=crop&q=80",
        notes: "Dán sẵn vỉ lưới inox 304 không gỉ 10x10cm | Hạ thủy ngay không cần buộc | Ưa nước mát < 26°C",
      },
      {
        id: "prod_srv_setup60",
        sku: "TS-SRV-SETUP60",
        name: "Gói Setup Hồ Thủy Sinh Iwagumi Trọn Gói 60x40x40cm",
        category: "Setup Hồ Trọn Gói & Bảo Dưỡng",
        description: "Bao gồm kính siêu trong 60x40x40cm 8mm mài vi tính, đá da voi/Seiryu, thảm trân châu ngọc trai, phân nền ADA, đèn RGB Chihiros, lọc thùng và bình CO2.",
        unit: "Bể",
        retailPrice: 8500000,
        wholesalePrice: 7200000,
        vipPrice: 6800000,
        isActive: true,
        imageUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80",
        notes: "Trọn gói thiết bị & cây xanh tận nhà | Tặng 1 tháng chăm sóc miễn phí | Bảo hành hồ 24 tháng",
      },
      {
        id: "prod_srv_setup120",
        sku: "TS-SRV-SETUP120",
        name: "Gói Setup Bể Thủy Sinh Biotope Cao Cấp 120x50x50cm",
        category: "Setup Hồ Trọn Gói & Bảo Dưỡng",
        description: "Dự án bể lớn sảnh lễ tân/văn phòng: Kính siêu trong 12mm, tủ gỗ sồi tự nhiên chống ẩm, lũa cổ thụ rừng nhiệt đới, phối ráy nana, bucep, cá đàn tetra.",
        unit: "Dự án",
        retailPrice: 28000000,
        wholesalePrice: 24000000,
        vipPrice: 22000000,
        isActive: true,
        imageUrl: "https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?w=600&auto=format&fit=crop&q=80",
        notes: "Dự án sảnh lễ tân/văn phòng VIP | Thiết kế layout 3D trước khi thi công | Hỗ trợ bảo dưỡng trọn đời",
      },
      {
        id: "prod_srv_maintain",
        sku: "TS-SRV-MAINTAIN",
        name: "Gói Chăm Sóc & Bảo Dưỡng Bể Thủy Sinh Định Kỳ 3 Tháng",
        category: "Setup Hồ Trọn Gói & Bảo Dưỡng",
        description: "Kỹ thuật viên đến tận nơi mỗi 2 tuần: Thay nước, cắt tỉa cây, đo thông số nước, châm phân vi lượng và diệt rêu hại.",
        unit: "Gói/3 Tháng",
        retailPrice: 3600000,
        wholesalePrice: 3000000,
        vipPrice: 2700000,
        isActive: true,
        imageUrl: "https://images.unsplash.com/photo-1516684732162-798a0062be99?w=600&auto=format&fit=crop&q=80",
        notes: "Kỹ thuật viên đến tận nơi 2 tuần/lần | Đo kiểm pH, kH, TDS | Cung cấp sẵn thuốc vi sinh & phân bón chuyên dụng",
      },
    ],

    deals: [],

    tasks: [],

    interactions: [],

    orders: [],

    documents: [
      {
        id: "doc_1",
        title: "Catalog Cây Thủy Sinh & Bố Cục Thủy Sinh Nghệ Thuật 2026",
        category: "CATALOG",
        fileSize: "5.4 MB",
        fileType: "PDF",
        url: "#",
        allowedRoles: ["ADMIN", "LEADER", "SALE"],
        description: "Bản giới thiệu đầy đủ các dòng ráy, bucep, tiêu thảo, cây tiền cảnh và các mẫu bể đẹp nhất.",
        updatedAt: subDays(10),
      },
      {
        id: "doc_2",
        title: "Bảng Giá Sỉ Cây Cấy Mô In-Vitro & Ráy Dành Cho Đại Lý Toàn Quốc",
        category: "PRICE_LIST",
        fileSize: "1.2 MB",
        fileType: "XLSX",
        url: "#",
        allowedRoles: ["ADMIN", "LEADER"],
        description: "Chính sách giá sỉ đại lý, chiết khấu theo số lượng (50-100-500 cốc) và bảo hiểm vận chuyển.",
        updatedAt: subDays(5),
      },
      {
        id: "doc_3",
        title: "Cẩm Nang Hướng Dẫn Trồng & Chăm Sóc Cây Thủy Sinh Cho Người Mới",
        category: "BROCHURE",
        fileSize: "3.2 MB",
        fileType: "PDF",
        url: "#",
        allowedRoles: ["ADMIN", "LEADER", "SALE"],
        description: "Tài liệu gửi khách: Cách cắm cây, chỉnh CO2, ánh sáng và cách phòng chống rêu hại thời kỳ đầu.",
        updatedAt: subDays(15),
      },
      {
        id: "doc_4",
        title: "Hợp Đồng Thi Công & Bảo Hành Bể Thủy Sinh Trọn Gói",
        category: "CONTRACT_TEMPLATE",
        fileSize: "850 KB",
        fileType: "DOCX",
        url: "#",
        allowedRoles: ["ADMIN", "LEADER", "SALE"],
        description: "Mẫu hợp đồng pháp lý có điều khoản cam kết cây sống 100% sau 14 ngày cắm và bảo trì thiết bị.",
        updatedAt: subDays(8),
      },
    ],

    salesScripts: [
      {
        id: "sc_1",
        title: "Xử lý từ chối: 'Cây thủy sinh ship đi xa có sợ bị dập nát, rữa lá không?'",
        category: "OBJECTION_HANDLING",
        questionOrScenario: "Khách hàng mua online lo ngại cây vận chuyển 2-3 ngày bị úng rữa hoặc chết cây.",
        recommendedResponse: "Dạ anh/chị hoàn toàn yên tâm ạ! Tất cả cây thủy sinh bên em trước khi gửi đều được ráo nước, đóng túi nilon bơm căng khí oxy và đóng trong thùng xốp giữ nhiệt chuyên dụng chống va đập. Đặc biệt bên em có chính sách Bảo hành sống khỏe 100%: khi nhận hàng nếu cây có bất kỳ dấu hiệu rữa lá hay dập nát nào, anh chị chỉ cần chụp ảnh lại, bên em sẽ gửi bù cây mới hoàn toàn miễn phí ngay trong ngày ạ!",
        tips: "Nhấn mạnh vào quy chuẩn đóng gói thùng xốp giữ nhiệt chuyên nghiệp và chính sách bảo hành 1 đổi 1 không rủi ro.",
        allowedRoles: ["ADMIN", "LEADER", "SALE"],
      },
      {
        id: "sc_2",
        title: "Xử lý từ chối: 'Giá cây bên em cao hơn các shop khác hoặc hàng trôi nổi'",
        category: "OBJECTION_HANDLING",
        questionOrScenario: "Khách hàng so sánh giá với các shop bán cây khai thác tự nhiên hoặc hàng chợ.",
        recommendedResponse: "Dạ em rất hiểu tâm lý so sánh giá của anh chị. Nhưng chơi thủy sinh thì chất lượng cây quyết định 80% vẻ đẹp của bể: Cây bên em là dòng cấy mô in-vitro và cây ươm tại trại sạch 100% ốc hại, mầm rêu hại và sán. Cây form lá đã thuần nước, về cắm vào bể là bám rễ đâm chồi ngay, không bị sốc nước rữa lá như hàng khai thác trôi nổi. Mua rẻ hơn vài chục nghìn nhưng lây rêu hại ra cả bể thì chi phí xử lý sau này tốn kém hơn rất nhiều ạ!",
        tips: "Đánh trúng nỗi sợ lớn nhất của người chơi thủy sinh là 'ốc hại' và 'rêu hại' lây lan từ nguồn cây bẩn.",
        allowedRoles: ["ADMIN", "LEADER", "SALE"],
      },
      {
        id: "sc_3",
        title: "Tư vấn cho khách mới: 'Bể mới làm có khó chăm không và cần đầu tư những gì?'",
        category: "COLD_CALL",
        questionOrScenario: "Khách hàng muốn làm bể thủy sinh nhưng sợ khó chăm, sợ cây chết.",
        recommendedResponse: "Chào anh/chị, thủy sinh hiện nay rất đơn giản và nhàn nhờ các thiết bị tự động hóa thông minh. Với người mới, em khuyên anh chị nên bắt đầu với các dòng cây khỏe, dễ sống như Ráy Nana, Dương Xỉ hoặc Tiêu Thảo phối lũa đá - dòng này không cần nhiều CO2 hay đèn đắt tiền mà vẫn xanh tốt quanh năm. Bên em có sẵn các gói setup trọn gói từ A-Z, kỹ thuật viên đến tận nhà lắp đặt và hướng dẫn chi tiết, anh chị chỉ việc ngắm cá và cây thôi ạ!",
        tips: "Gợi ý những dòng cây bất tử (ráy, dương xỉ) để tạo sự tự tin cho người mới bắt đầu.",
        allowedRoles: ["ADMIN", "LEADER", "SALE"],
      },
      {
        id: "sc_4",
        title: "Xử lý câu hỏi: 'Bể mới cắm bao lâu thì bị rêu hại và cách xử lý thế nào?'",
        category: "FAQ",
        questionOrScenario: "Khách hàng lo lắng về việc bùng phát rêu hại (rêu tóc, tảo nâu, rêu chùm đen).",
        recommendedResponse: "Dạ trong 2-3 tuần đầu khi hệ vi sinh chưa ổn định, ánh sáng dư thừa có thể sinh tảo nâu nhẹ. Bên em sẽ hướng dẫn anh chị quy trình chuẩn: Bật đèn 6 tiếng/ngày, thay nước 30% mỗi tuần 2 lần trong tháng đầu, và thả một đội dọn bể mini gồm tép Amano + ốc Nerita. Đảm bảo bể của anh chị luôn trong vắt và cây quang hợp thở bong bóng oxy đều đặn ạ!",
        tips: "Cung cấp kiến thức chuyên sâu tạo sự tin tưởng tuyệt đối về mặt kỹ thuật cho khách hàng.",
        allowedRoles: ["ADMIN", "LEADER", "SALE"],
      },
    ],
  };
}
